### ISSUE TITLE
Error "Chatter.settings Not available for deploy for this API version" when creating scratch org

### ISSUE THREAD

**Issue by markirvineCV** [SFDO-Tooling/CumulusCI-Test#183]
Getting error when working through the tutorial at the step to create a scratch org:
https://cumulusci.readthedocs.io/en/latest/tutorial.html#using-salesforce-dx-scratch-orgs

```
Error  shape/settings/Chatter.settings              settings/Chatter.settings              Not available for deploy for this API version
Error  shape/settings/LightningExperience.settings  settings/LightningExperience.settings  Not available for deploy for this API version

ERROR running force:org:create:  Failed to deploy settings to scratch org.
```
I just installed cci 3.10. on mac.

When I try the sfdx command I get the same error.

I edited orgs/dev.json to remove:

```
  "settings": {
    "chatterSettings": {
      "enableChatter": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    }
  }
```

And now it works fine. Seems to be some issue with the settings?

**Comment by davisagli** [comment]
@markirvineCV it's working for me. Some things to check:
- Run `sfdx update` to make sure you have the latest version of sfdx.
- Does `sfdx force:config:get apiVersion` show a specific API version, or an empty value?

**Comment by markirvineCV** [comment]
@davisagli  I ran sfdx update:

```
Admins-MacBook-Pro:CumulusCI-Test admin$ sfdx update
sfdx-cli: Updating CLI from 7.25.3-16d54c01ee to 7.31.0-6a986f8be5... done
sfdx-cli: Updating CLI... done
warning "salesforcedx > force-language-services > @salesforce/command > @oclif/command@1.5.18" has unmet peer dependency "@oclif/config@^1".
sfdx-cli: Updating plugins... done
```
The API version is blank:
```
Admins-MacBook-Pro:CumulusCI-Test admin$ sfdx force:config:get apiVersion
=== Config
Name        Value
──────────  ─────
apiVersion
```
It still fails with the ame errors.

**Comment by davisagli** [comment]
@markirvineCV ok. I've had one other report of this but don't know the cause yet. I'll keep you posted if I figure something out.

**Comment by davisagli** [comment]
@markirvineCV I just updated the package API version to 47.0 which should help with this.
